title: "Ahmed Elsherif | Embedded Systems Engineer"
description: "Embedded systems, PCB design, and electronics projects portfolio."
theme: minima
baseurl: "/portfolio"
url: "https://ahmedxelsherif.github.io"
