title: "Ahmed Elsherif Portfolio"
description: "Embedded systems, PCB design, and electronics projects portfolio."
baseurl: "/portfolio"
url: "https://ahmedxelsherif.github.io"
theme: null
markdown: kramdown

collections:
  projects:
    output: true
    permalink: /projects/:path/

defaults:
  - scope:
      path: ""
      type: "projects"
    values:
      layout: "project"

sass:
  style: compressed
